stages:
  - build_media
  - build_prog
  - build_unity
  - build_otros
  - deploy

default:
  image: node:22
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/

build_media:
  stage: build_media
  script:
    - npm ci
    - echo "Building the site..."
    - npx quartz build  # Genera los archivos en `public/`
  artifacts:
    paths:
      - public/zz-Media
    expire_in: 1 hour  # Opcional: Limpia el artefacto después del despliegue

build_prog:
  stage: build_prog
  script:
    - npm ci
    - echo "Building the site..."
    - npx quartz build  # Genera los archivos en `public/`
  artifacts:
    paths:
      - public/Programación
    expire_in: 1 hour  # Opcional: Limpia el artefacto después del despliegue



build_unity:
  stage: build_unity
  script:
    - npm ci
    - echo "Building the site..."
    - npx quartz build  # Genera los archivos en `public/`
  artifacts:
    paths:
      - public/Unity
      - public/zz-Media-Unity
    expire_in: 1 hour  # Opcional: Limpia el artefacto después del despliegue

build_otros:
  stage: build_otros
  script:
    - npm ci
    - echo "Building the site..."
    - npx quartz build  # Genera los archivos en `public/`
  artifacts:
    paths:
      - public/Otros
    expire_in: 1 hour  # Opcional: Limpia el artefacto después del despliegue



pages:
  stage: deploy
  dependencies:
    - build_media
    - build_prog
    - build_unity  # Asegura que el job `build` se complete primero
    - build_otros
  script:
    - mv public/Otros public
    - mv public .public  # Renombra la carpeta (más eficiente que copiar)
    - mv .public public  # GitLab Pages espera los archivos en `public/`
  artifacts:
    paths:
      - public
  only:
    - main