stages:
  - build
  - deploy

image: node:22
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - echo "Building the site..."
    - npx quartz build 
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - mkdir .public
    #  - Get-ChildItem -Path . -Exclude .public | ForEach-Object { Copy-Item $_.FullName -Destination .public -Recurse -Force }
    - cp -r * .public # version Linux
    - mv .public public
  artifacts:
    paths:
      - public
    exclude:
      - node_modules/  # Excluir dependencias innecesarias
      - tmp/          # Excluir archivos temporales
  only:
    - main
