stages:
  - build
  - deploy

image: node:22
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - echo "Building the site..."
    - npx quartz build  # Genera los archivos en `public/`
  artifacts:
    paths:
      - public
    expire_in: 1 hour  # Opcional: Limpia el artefacto después del despliegue

pages:
  stage: deploy
  dependencies:
    - build  # Asegura que el job `build` se complete primero
  script:
    - mv public .public  # Renombra la carpeta (más eficiente que copiar)
    - mv .public public  # GitLab Pages espera los archivos en `public/`
  artifacts:
    paths:
      - public
  only:
    - main